name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build executable for ${{ matrix.architecture }}
        run: |
          docker run --rm --platform linux/${{ matrix.architecture }} \
            -v ${{ github.workspace }}:/app \
            -w /app python:3.11 bash -c "\
              curl -LsSf https://astral.sh/uv/install.sh | sh && \
              export PATH=\"/root/.local/bin:$PATH\" && \
              uv pip install -e .[dev] && \
              python build.py && \
              cp dist/browser-agent /app/browser-agent-ubuntu-${{ matrix.architecture }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: browser-agent-ubuntu-${{ matrix.architecture }}
          path: browser-agent-ubuntu-${{ matrix.architecture }}
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/browser-agent-ubuntu-amd64/browser-agent-ubuntu-amd64
            artifacts/browser-agent-ubuntu-arm64/browser-agent-ubuntu-arm64
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 